### ISSUE TITLE
support for puppet 6+

### ISSUE THREAD

**Issue by surajbora1** [tpdownes/puppet-sysctl#4]
Hi Team,
We were using tpdownes/sysctl module in puppet 4+ (<6). But now current version of puppet is 6+ (6.15) and as per support matrix, supported puppet version is Puppet >= 4.9.0 < 6.0.0.

Can you please confirm is this module compatible with puppet version 6+ or is there any development going on to support this.

**Comment by tpdownes** [comment]
I switched to https://forge.puppet.com/herculesteam/augeasproviders_sysctl in my own work a while back. The git commit where I made the switch makes it look effortless.

**Comment by surajbora1** [comment]
Thanks @tpdownes for update.
